### ISSUE TITLE
Default Behaviour of Enact InputField is identifying as a bug by LG Webos QA Team.

### ISSUE THREAD

**Issue by javadsalman** [enactjs/enact#3283] opened 2024-09-28 06:19 UTC
### Category
* [ ] Other

### Description
My application can't pass the quality check of the LG Webos QA Team because of the default behavior of Enact InputField. When the input is focused and the cursor is at the beginning of the value text and you press the left arrow on the keyboard spotlight leaves the input and when the cursor is at the end of the value text and you press the right arrow on the keyboard spotlight leaves this time as well. It's the built-in, default behavior of Enact InputField but the QA Team identifies this behavior as a bug and rejects my application. I added two videos below which the QA Team provided.

### Environment
Doesn't make a difference

**Enact version: 4.7.8**

### Videos
https://youtu.be/UskSpnxDGSw
https://youtu.be/NnGF15uSXg0

**Comment by MikyungKim** [comment] 2024-09-30 05:49
Dear @javadsalman,
I'm so sorry that your application got rejected by the default behavior of Enact InputField. I'm not sure why QA Team did that but as long as I know, the current behavior is expected behavior. You could see the same behavior from Settings > Support > TV Information > Device Name. Why don't you record the built-in app (Settings) behavior and report that this is the expected behavior?
Thank you.

**Comment by javadsalman** [comment] 2024-09-30 13:19
Thanks for your consideration @MikyungKim. I informed them at the first attempt but they identified this feature as a bug again. That's why I provided two videos. I already bypassed this feature from the code side but it'd be better if you'd inform the QA team if you have a connection with them. Because I think this feature is useful and mustn't be removed

**Comment by MikyungKim** [comment] 2024-10-02 00:51
@javadsalman, I'm sorry that I have no contact information at this point. Would you be able to provide me an e-mail address or anything?

**Comment by javadsalman** [comment] 2024-10-02 16:08
@MikyungKim, I can't access our sent feedback right now but I share an email from the QA team that sends results to us below.
hyohoon.na@lgepartner.com

**Comment by javadsalman** [comment] 2024-10-05 01:33
@MikyungKim They expect the spotlight not to leave input focus by right or left direction keys even if the cursor is at the borderline.

**Comment by MikyungKim** [comment] 2024-10-08 00:28
@javadsalman, Sorry for the delayed reply since I was out of office. Let me contact the person you mentioned and get back to you as soon as I get the answer.

**Comment by MikyungKim** [comment] 2024-10-08 01:51
Hello @javadsalman, I contacted the QA team and he will see if he can close the issue. I think it could close soon.
But the issue related the InputField is P3 issue which is not a blocker for acceptance of your app. He said you need to fix P2 bug. I'm closing this issue since the current behavior is the expecting behavior. Thank you!

**Closed by MikyungKim** 2024-10-08 01:51 UTC
